import type { Movimiento, ClienteMRR, Proyecto, Deuda, Presupuesto, CuentaPorCobrar } from '../types';

// App arranca desde abril 2026.
export const mockProyectos: Proyecto[] = [];
export const mockPresupuestos: Presupuesto[] = [];

// Saldo inicial SM DIGITALS: 1.013.000 COP
export const mockSaldoInicial: Movimiento = {
  id: 'saldo_inicial_smdigitals',
  fecha: '2026-04-01',
  periodo: '2026-04',
  año: 2026,
  mes: 4,
  unidad: 'SM DIGITALS',
  space_id: 'sp_smdigitals',
  tipo_movimiento: 'Ingreso',
  categoria: 'Inicial',
  subcategoria: 'Saldo inicial',
  cliente_proveedor: 'Saldo inicial',
  descripcion: 'Saldo inicial Bancolombia',
  metodo_pago: 'Bancolombia',
  monto: 1_013_000,
  recurrente: false,
  estado: 'Pagado',
  impacto: 'Core',
  cuenta: 'Bancolombia',
  created_at: '2026-04-01T00:00:00Z',
};

// Clientes que me deben dinero
export const mockCuentasPorCobrar: CuentaPorCobrar[] = [
  {
    id: 'cxc_juan_tasama',
    cliente: 'Juan Tasama',
    monto: 4_900_000,
    fecha_emision: '2026-04-01',
    descripcion: 'Servicio profesional',
    estado: 'Pendiente',
    monto_cobrado: 0,
    created_at: '2026-04-01T08:00:00Z',
  },
  {
    id: 'cxc_victor_chalarca',
    cliente: 'Victor Chalarca',
    monto: 620_000,
    fecha_emision: '2026-04-05',
    descripcion: 'Servicio profesional',
    estado: 'Pendiente',
    monto_cobrado: 0,
    created_at: '2026-04-05T08:00:00Z',
  },
  {
    id: 'cxc_juan_lomo_digital',
    cliente: 'Juan Lomo Digital',
    monto: 500_000,
    fecha_emision: '2026-04-10',
    descripcion: 'Servicio profesional',
    estado: 'Pendiente',
    monto_cobrado: 0,
    created_at: '2026-04-10T08:00:00Z',
  },
];

// Gastos fijos recurrentes de abril 2026.
// Marcados como recurrente=true para que la proyección los detecte como plantillas mensuales.
export const mockMovimientos: Movimiento[] = [
  mockSaldoInicial,
  {
    id: 'gf_oficina_abr',
    fecha: '2026-04-01',
    periodo: '2026-04',
    año: 2026,
    mes: 4,
    unidad: 'SM DIGITALS',
    space_id: 'sp_smdigitals',
    tipo_movimiento: 'Gasto',
    categoria: 'Operativos',
    subcategoria: 'Oficina',
    cliente_proveedor: 'Arrendador',
    descripcion: 'Alquiler oficina',
    metodo_pago: 'Transferencia',
    monto: 750_000,
    recurrente: true,
    estado: 'Pagado',
    impacto: 'Core',
    cuenta: 'Bancolombia',
    created_at: '2026-04-01T08:00:00Z',
  },
  {
    id: 'gf_internet_abr',
    fecha: '2026-04-01',
    periodo: '2026-04',
    año: 2026,
    mes: 4,
    unidad: 'SM DIGITALS',
    space_id: 'sp_smdigitals',
    tipo_movimiento: 'Gasto',
    categoria: 'Operativos',
    subcategoria: 'Internet/Celular',
    cliente_proveedor: 'Movistar',
    descripcion: 'Internet y celular',
    metodo_pago: 'Transferencia',
    monto: 75_000,
    recurrente: true,
    estado: 'Pagado',
    impacto: 'Core',
    cuenta: 'Bancolombia',
    created_at: '2026-04-01T08:00:00Z',
  },
  {
    id: 'gf_servicios_abr',
    fecha: '2026-04-01',
    periodo: '2026-04',
    año: 2026,
    mes: 4,
    unidad: 'SM DIGITALS',
    space_id: 'sp_smdigitals',
    tipo_movimiento: 'Gasto',
    categoria: 'Operativos',
    subcategoria: 'Servicios públicos',
    cliente_proveedor: 'EPM',
    descripcion: 'Servicios públicos',
    metodo_pago: 'Transferencia',
    monto: 150_000,
    recurrente: true,
    estado: 'Pagado',
    impacto: 'Core',
    cuenta: 'Bancolombia',
    created_at: '2026-04-01T08:00:00Z',
  },
  {
    id: 'gf_barberia_abr',
    fecha: '2026-04-20',
    periodo: '2026-04',
    año: 2026,
    mes: 4,
    unidad: 'Personal',
    space_id: 'sp_personal',
    tipo_movimiento: 'Gasto',
    categoria: 'Bienestar',
    subcategoria: 'Barbería',
    cliente_proveedor: 'Barbería',
    descripcion: 'Corte mensual',
    metodo_pago: 'Efectivo',
    monto: 100_000,
    recurrente: true,
    estado: 'Pagado',
    impacto: 'Privado',
    cuenta: 'Billetera',
    created_at: '2026-04-20T08:00:00Z',
  },
    {
      id: 'may_gasto_comidas',
      fecha: '2026-05-15',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Ocio',
      subcategoria: 'Comidas',
      cliente_proveedor: 'Varios',
      descripcion: 'Comidas',
      metodo_pago: 'Efectivo',
      monto: 247000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-15T08:00:00Z',
    },
    {
      id: 'may_gasto_transporte',
      fecha: '2026-05-15',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Transporte',
      subcategoria: 'Uber',
      cliente_proveedor: 'Uber',
      descripcion: 'Transporte (Uber/Ubers)',
      metodo_pago: 'Tarjeta',
      monto: 44500,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-15T08:00:00Z',
    },
    {
      id: 'may_gasto_gym',
      fecha: '2026-05-05',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Bienestar',
      subcategoria: 'Gimnasio',
      cliente_proveedor: 'Gym',
      descripcion: 'Gym',
      metodo_pago: 'Tarjeta',
      monto: 160000,
      recurrente: true,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Bancolombia',
      created_at: '2026-05-05T08:00:00Z',
    },
    {
      id: 'may_gasto_tarjeta',
      fecha: '2026-05-20',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_marcapersonal',
      tipo_movimiento: 'Gasto',
      categoria: 'Deuda',
      subcategoria: 'Tarjeta de crédito',
      cliente_proveedor: 'Banco',
      descripcion: 'Tarjeta de crédito',
      metodo_pago: 'Transferencia',
      monto: 48000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Bancolombia',
      created_at: '2026-05-20T08:00:00Z',
    },
    {
      id: 'may_gasto_moto',
      fecha: '2026-05-10',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Transporte',
      subcategoria: 'Moto',
      cliente_proveedor: 'Taller',
      descripcion: 'Moto/Batería',
      metodo_pago: 'Efectivo',
      monto: 100000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-10T08:00:00Z',
    },
    {
      id: 'may_gasto_vino',
      fecha: '2026-05-12',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Ocio',
      subcategoria: 'Ocio',
      cliente_proveedor: 'Licorera',
      descripcion: 'Vino rosado',
      metodo_pago: 'Efectivo',
      monto: 65000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-12T08:00:00Z',
    },
    {
      id: 'may_gasto_pastillas',
      fecha: '2026-05-15',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Bienestar',
      subcategoria: 'Salud',
      cliente_proveedor: 'Farmacia',
      descripcion: 'Pastillas Andrea',
      metodo_pago: 'Efectivo',
      monto: 26000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-15T08:00:00Z',
    },
    {
      id: 'may_gasto_potenciador',
      fecha: '2026-05-15',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Bienestar',
      subcategoria: 'Suplementos',
      cliente_proveedor: 'Tienda',
      descripcion: 'Potenciador',
      metodo_pago: 'Efectivo',
      monto: 30000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-15T08:00:00Z',
    },
    {
      id: 'may_gasto_elecciones',
      fecha: '2026-05-25',
      periodo: '2026-05',
      año: 2026,
      mes: 5,
      unidad: 'Personal',
      space_id: 'sp_personal',
      tipo_movimiento: 'Gasto',
      categoria: 'Ocio',
      subcategoria: 'Varios',
      cliente_proveedor: 'Varios',
      descripcion: 'Elecciones',
      metodo_pago: 'Efectivo',
      monto: 20000,
      recurrente: false,
      estado: 'Pagado',
      impacto: 'Privado',
      cuenta: 'Billetera',
      created_at: '2026-05-25T08:00:00Z',
    }

];

// Deudas activas con sus cuotas mensuales.
// fecha_pago = día del mes en que se debe pagar la cuota (puedes editarlo en la app).
// El préstamo de $4.100.000 viene sin cuota â€” ajustar cuando definas el plan.
export const mockDeudas: Deuda[] = [
  {
    id: 'deuda_victor',
    acreedor: 'Víctor',
    tipo: 'Préstamo personal',
    saldo_inicial: 15_660_000,
    cuota_mensual: 500_000,
    pagado: 0,
    saldo_restante: 15_660_000,
    fecha_pago: '15',
    estado: 'Al día',
  },
  {
    id: 'deuda_credito_grande',
    acreedor: 'Banco - Crédito grande',
    tipo: 'Crédito bancario',
    saldo_inicial: 28_786_385,
    cuota_mensual: 785_000,
    pagado: 0,
    saldo_restante: 28_786_385,
    fecha_pago: '30',
    estado: 'Al día',
  },
  {
    id: 'deuda_tarjeta',
    acreedor: 'Tarjeta de crédito',
    tipo: 'Tarjeta',
    saldo_inicial: 3_000_000,
    cuota_mensual: 1_137_000,
    pagado: 0,
    saldo_restante: 3_000_000,
    fecha_pago: '10',
    estado: 'Al día',
  },
  {
    id: 'deuda_prestamo',
    acreedor: 'Préstamo',
    tipo: 'Préstamo',
    saldo_inicial: 4_100_000,
    cuota_mensual: 4_100_000,
    pagado: 0,
    saldo_restante: 4_100_000,
    fecha_pago: '25',
    estado: 'Al día',
  },
];

// 6 clientes recurrentes activos con sus reglas de distribución.
// margen_30 (default): costo operativo 150k + 30% del margen.
// pago_30 (Impulsy): solo 30% del pago total como ahorro.
export const mockClientesMRR: ClienteMRR[] = [
  {
    id: 'mrr_santorini_wa',
    cliente: 'Santorini WhatsApp',
    servicio: 'Bot de WhatsApp',
    valor_mensual: 400_000,
    dia_cobro: 15,
    estado: 'Activo',
    fecha_inicio: '2026-04-01',
    metodo_pago: 'Transferencia',
    costo_operativo: 150_000,
    regla_ahorro: 'margen_30',
    ahorro_pct: 30,
  },
  {
    id: 'mrr_santorini_soporte',
    cliente: 'Santorini Soporte',
    servicio: 'Soporte mensual',
    valor_mensual: 685_000,
    dia_cobro: 15,
    estado: 'Activo',
    fecha_inicio: '2026-04-01',
    metodo_pago: 'Transferencia',
    costo_operativo: 150_000,
    regla_ahorro: 'margen_30',
    ahorro_pct: 30,
  },
  {
    id: 'mrr_kp_skincare',
    cliente: 'KP Skincare',
    servicio: 'IA + Soporte',
    valor_mensual: 870_000,
    dia_cobro: 20,
    estado: 'Activo',
    fecha_inicio: '2026-04-01',
    metodo_pago: 'Transferencia',
    costo_operativo: 150_000,
    regla_ahorro: 'margen_30',
    ahorro_pct: 30,
  },
  {
    id: 'mrr_kp_masivos',
    cliente: 'KP Skincare Masivos',
    servicio: 'Mensajes masivos',
    valor_mensual: 725_000,
    dia_cobro: 20,
    estado: 'Activo',
    fecha_inicio: '2026-04-01',
    metodo_pago: 'Transferencia',
    costo_operativo: 150_000,
    regla_ahorro: 'margen_30',
    ahorro_pct: 30,
  },
  {
    id: 'mrr_impulsy_tasks',
    cliente: 'Impulsy Tasks',
    servicio: 'Tasks',
    valor_mensual: 95_000,
    dia_cobro: 1,
    estado: 'Activo',
    fecha_inicio: '2026-04-01',
    metodo_pago: 'Transferencia',
    costo_operativo: 0,
    regla_ahorro: 'pago_30',
    ahorro_pct: 30,
  },
  {
    id: 'mrr_la_vera_massa',
    cliente: 'La Vera Massa',
    servicio: 'Servicio mensual',
    valor_mensual: 350_000,
    dia_cobro: 5,
    estado: 'Activo',
    fecha_inicio: '2026-04-01',
    metodo_pago: 'Transferencia',
    costo_operativo: 150_000,
    regla_ahorro: 'margen_30',
    ahorro_pct: 30,
  },
];

