import type { Movimiento, ClienteMRR, Proyecto, Deuda, Presupuesto } from '../types';

const generateFixedExpenses = (period: string, año: number, mes: number): Movimiento[] => [
  { id: `g-ofi-${period}`, fecha: `${period}-01`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Oficina', cliente_proveedor: 'Arrendador', descripcion: 'Alquiler oficina', metodo_pago: 'Transferencia', monto: 750000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-01T08:00:00Z` },
  { id: `g-int-${period}`, fecha: `${period}-01`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Internet/Celular', cliente_proveedor: 'Movistar', descripcion: 'Internet y celular', metodo_pago: 'Transferencia', monto: 75000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-01T08:00:00Z` },
  { id: `g-ser-${period}`, fecha: `${period}-01`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Servicios', cliente_proveedor: 'EPM', descripcion: 'Servicios públicos', metodo_pago: 'Transferencia', monto: 150000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-01T08:00:00Z` },
  { id: `g-gas-${period}`, fecha: `${period}-05`, periodo: period, año, mes, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Primax', descripcion: 'Gasolina carro', metodo_pago: 'Efectivo', monto: 300000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: `${period}-05T08:00:00Z` },
  { id: `g-n8n-${period}`, fecha: `${period}-10`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Herramientas', subcategoria: 'Suscripción', cliente_proveedor: 'n8n', descripcion: 'Suscripción n8n', metodo_pago: 'Tarjeta', monto: 80000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: `${period}-10T08:00:00Z` },
  { id: `g-anti-${period}`, fecha: `${period}-10`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Herramientas', subcategoria: 'Suscripción', cliente_proveedor: 'Antigravity', descripcion: 'Suscripción Antigravity', metodo_pago: 'Tarjeta', monto: 80000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: `${period}-10T08:00:00Z` },
  { id: `g-dvictor-${period}`, fecha: `${period}-15`, periodo: period, año, mes, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Víctor', cliente_proveedor: 'Víctor', descripcion: 'Pago deuda Víctor', metodo_pago: 'Transferencia', monto: 500000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: `${period}-15T08:00:00Z` },
  { id: `g-dbanco-${period}`, fecha: `${period}-30`, periodo: period, año, mes, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Banco Nacional', cliente_proveedor: 'Banco Nacional', descripcion: 'Cuota crédito bancario', metodo_pago: 'Transferencia', monto: 900000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: `${period}-30T08:00:00Z` },
  { id: `g-gym-${period}`, fecha: `${period}-02`, periodo: period, año, mes, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Gym', cliente_proveedor: 'SmartFit', descripcion: 'Mensualidad Gym', metodo_pago: 'Tarjeta', monto: 160000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: `${period}-02T08:00:00Z` },
  { id: `g-barb-${period}`, fecha: `${period}-20`, periodo: period, año, mes, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Barbería', cliente_proveedor: 'Barber Shop', descripcion: 'Corte de cabello', metodo_pago: 'Efectivo', monto: 100000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: `${period}-20T08:00:00Z` },
  
  // MRR — Nombres reales
  { id: `f1-${period}`, fecha: `${period}-20`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare Soporte', cliente_proveedor: 'KP Skincare Soporte', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 745000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-20T08:00:00Z` },
  { id: `f2-${period}`, fecha: `${period}-20`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare IA', cliente_proveedor: 'KP Skincare IA', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 580000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-20T08:00:00Z` },
  { id: `f3-${period}`, fecha: `${period}-15`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini WhatsApp', cliente_proveedor: 'Motel Santorini WhatsApp', descripcion: 'Cobro Mensual', metodo_pago: 'Efectivo', monto: 516000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-15T08:00:00Z` },
  { id: `f4-${period}`, fecha: `${period}-01`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini 1', cliente_proveedor: 'Motel Santorini 1', descripcion: 'Cobro Mensual', metodo_pago: 'Efectivo', monto: 400000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-01T08:00:00Z` },
  { id: `f5-${period}`, fecha: `${period}-05`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'La Vera Massa', cliente_proveedor: 'La Vera Massa', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 350000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-05T08:00:00Z` },
  { id: `f6-${period}`, fecha: `${period}-10`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'S.O.S Tenis', cliente_proveedor: 'S.O.S Tenis', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 250000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-10T08:00:00Z` },
  { id: `f7-${period}`, fecha: `${period}-25`, periodo: period, año, mes, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Taowok', cliente_proveedor: 'Taowok', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 250000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: `${period}-25T08:00:00Z` },
];

export const mockMovimientos: Movimiento[] = [
  // ─────────────── ENERO 2026 ───────────────
  // Gastos fijos operativos
  { id: 'jan-ofi', fecha: '2026-01-01', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Oficina', cliente_proveedor: 'Arrendador', descripcion: 'Alquiler oficina', metodo_pago: 'Transferencia', monto: 750000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-01T08:00:00Z' },
  { id: 'jan-int', fecha: '2026-01-01', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Internet/Celular', cliente_proveedor: 'Movistar', descripcion: 'Internet y celular', metodo_pago: 'Transferencia', monto: 75000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-01T08:00:00Z' },
  { id: 'jan-ser', fecha: '2026-01-01', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Servicios', cliente_proveedor: 'EPM', descripcion: 'Servicios públicos', metodo_pago: 'Transferencia', monto: 150000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-01T08:00:00Z' },
  { id: 'jan-gas', fecha: '2026-01-05', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Primax', descripcion: 'Gasolina carro', metodo_pago: 'Efectivo', monto: 300000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-05T08:00:00Z' },
  { id: 'jan-n8n', fecha: '2026-01-10', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Herramientas', subcategoria: 'Suscripción', cliente_proveedor: 'n8n', descripcion: 'Suscripción n8n', metodo_pago: 'Tarjeta', monto: 80000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: '2026-01-10T08:00:00Z' },
  { id: 'jan-anti', fecha: '2026-01-10', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Herramientas', subcategoria: 'Suscripción', cliente_proveedor: 'Antigravity', descripcion: 'Suscripción Antigravity', metodo_pago: 'Tarjeta', monto: 80000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: '2026-01-10T08:00:00Z' },
  { id: 'jan-gym', fecha: '2026-01-02', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Gym', cliente_proveedor: 'SmartFit', descripcion: 'Mensualidad Gym', metodo_pago: 'Tarjeta', monto: 160000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-01-02T08:00:00Z' },

  // MRR Enero (4 clientes activos)
  { id: 'jan-mrr2', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare IA', cliente_proveedor: 'KP Skincare IA', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 580000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-15T08:00:00Z' },
  { id: 'jan-mrr3', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini WhatsApp', cliente_proveedor: 'Motel Santorini WhatsApp', descripcion: 'Cobro Mensual', metodo_pago: 'Efectivo', monto: 420000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-15T08:00:00Z' },
  { id: 'jan-mrr4', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini 1', cliente_proveedor: 'Motel Santorini 1', descripcion: 'Cobro Mensual', metodo_pago: 'Efectivo', monto: 400000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-15T08:00:00Z' },
  { id: 'jan-mrr5', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'La Vera Massa', cliente_proveedor: 'La Vera Massa', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 350000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-15T08:00:00Z' },

  // Ingresos variables enero
  { id: 'jan-v1', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Ingreso variable', subcategoria: 'Venta', cliente_proveedor: 'Venta carro Mazda', descripcion: 'Venta activo', metodo_pago: 'Transferencia', monto: 1500000, recurrente: false, estado: 'Pagado', impacto: 'Extraordinario', cuenta: 'Bancolombia', created_at: '2026-01-15T00:00:00Z' },
  { id: 'jan-v2', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Ingreso variable', subcategoria: 'Servicio', cliente_proveedor: 'Juan Kommo', descripcion: 'Trabajo Juan Kommo', metodo_pago: 'Transferencia', monto: 1000000, recurrente: false, estado: 'Pagado', impacto: 'Extraordinario', cuenta: 'Bancolombia', created_at: '2026-01-15T00:00:00Z' },
  { id: 'jan-v3', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Proyecto', subcategoria: 'Consultoría', cliente_proveedor: 'Frei', descripcion: 'Proyecto Frei', metodo_pago: 'Transferencia', monto: 1000000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-15T00:00:00Z', proyecto_id: 'p1' },
  { id: 'jan-v4', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Proyecto', subcategoria: 'Retainer', cliente_proveedor: 'Cluenza', descripcion: 'Pago Cluenza', metodo_pago: 'Transferencia', monto: 800000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-22T00:00:00Z', proyecto_id: 'p2' },
  { id: 'jan-v5', fecha: '2026-01-15', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Ingreso variable', subcategoria: 'Servicio', cliente_proveedor: 'M-Masivos', descripcion: 'M-Masivos', metodo_pago: 'Transferencia', monto: 350000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-01-15T00:00:00Z' },

  // Gastos variables enero
  { id: 'jan-g1',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Tarjeta', cliente_proveedor: 'Tarjeta crédito', descripcion: 'Pago tarjeta crédito', metodo_pago: 'Transferencia', monto: 2000000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g2',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Banco', cliente_proveedor: 'Banco Nacional', descripcion: 'Pago crédito bancario', metodo_pago: 'Transferencia', monto: 1900000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g3',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Regalo', cliente_proveedor: 'Ana', descripcion: 'Regalo Ana (hermana)', metodo_pago: 'Transferencia', monto: 350000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g4',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Regalo', cliente_proveedor: 'Ángela', descripcion: 'Regalo Ángela', metodo_pago: 'Transferencia', monto: 100000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g5',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Suplementos', cliente_proveedor: 'Suplementos', descripcion: 'Pre-entreno', metodo_pago: 'Efectivo', monto: 15000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g6',  fecha: '2026-01-24', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Ocio', subcategoria: 'Salida', cliente_proveedor: 'Varios', descripcion: 'Sábado 24 enero', metodo_pago: 'Efectivo', monto: 100000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-24T00:00:00Z' },
  { id: 'jan-g7',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Religioso', subcategoria: 'Ofrendas', cliente_proveedor: 'Iglesia', descripcion: 'Velas Virgen', metodo_pago: 'Efectivo', monto: 30000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g8',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Comida', cliente_proveedor: 'Familia', descripcion: 'Comida familia', metodo_pago: 'Efectivo', monto: 50000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g9',  fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Comida', cliente_proveedor: 'Familia', descripcion: 'Comidas familia', metodo_pago: 'Efectivo', monto: 100000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g10', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Tarjeta', cliente_proveedor: 'Tarjeta crédito', descripcion: 'Pago tarjeta (abono)', metodo_pago: 'Transferencia', monto: 209000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g11', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Seguridad Social', subcategoria: 'ARUS', cliente_proveedor: 'ARUS', descripcion: 'ARUS seguridad social', metodo_pago: 'Transferencia', monto: 70000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g12', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Ocio', subcategoria: 'Casino', cliente_proveedor: 'Casino', descripcion: 'Casino', metodo_pago: 'Efectivo', monto: 200000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g13', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Tarjeta', cliente_proveedor: 'Tarjeta crédito', descripcion: 'Pago crédito tarjeta (abono)', metodo_pago: 'Transferencia', monto: 149000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g14', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'business', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Tarjeta', cliente_proveedor: 'Tarjeta pequeña', descripcion: 'Pago crédito tarjeta (abono pequeño)', metodo_pago: 'Transferencia', monto: 14000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g15', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Mascotas', subcategoria: 'Veterinaria', cliente_proveedor: 'Animal X', descripcion: 'Animal X', metodo_pago: 'Efectivo', monto: 160000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g16', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Barbería', cliente_proveedor: 'Barbería', descripcion: 'Corte', metodo_pago: 'Efectivo', monto: 50000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g17', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Barbería', cliente_proveedor: 'Barbería', descripcion: 'Corte', metodo_pago: 'Efectivo', monto: 20000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },
  { id: 'jan-g18', fecha: '2026-01-20', periodo: '2026-01', año: 2026, mes: 1, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Barbería', cliente_proveedor: 'Barbería', descripcion: 'Corte', metodo_pago: 'Efectivo', monto: 20000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-01-20T00:00:00Z' },

  // ─────────────── FEBRERO 2026 ───────────────
  ...generateFixedExpenses('2026-02', 2026, 2),

  // Gastos variables / extraordinarios febrero
  // feb-g1 (eliminado por duplicidad — ya está detallado en los equipos individuales)
  { id: 'feb-g2',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Inversión', subcategoria: 'Equipos', cliente_proveedor: 'Oficina', descripcion: 'Artefactos oficina (parte de compras)', metodo_pago: 'Tarjeta', monto: 800000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g3',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Salida', cliente_proveedor: 'Familia', descripcion: 'Almuerzo familia', metodo_pago: 'Transferencia', monto: 300000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g4',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Regalo', cliente_proveedor: 'Hermana', descripcion: 'Regalo hermana', metodo_pago: 'Transferencia', monto: 133000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g5',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Regalo', cliente_proveedor: 'Hermana', descripcion: 'Regalo hermana', metodo_pago: 'Transferencia', monto: 100000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g6',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: "McDonald's", descripcion: "McDonald's", metodo_pago: 'Tarjeta', monto: 41700, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g7',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Frisby', descripcion: 'Frisby', metodo_pago: 'Tarjeta', monto: 33200, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g8',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Inversión', subcategoria: 'Equipos', cliente_proveedor: 'Oficina', descripcion: 'Monitor oficina', metodo_pago: 'Tarjeta', monto: 300000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g9',  fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Compras', subcategoria: 'Ropa', cliente_proveedor: 'Shein', descripcion: 'Shein', metodo_pago: 'Tarjeta', monto: 58000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g10', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Pollo Galeto', descripcion: 'Pollo Galeto', metodo_pago: 'Efectivo', monto: 54000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g11', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Pollo Galeto', descripcion: 'Pollo Galeto', metodo_pago: 'Efectivo', monto: 30000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g12', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Compras', subcategoria: 'Ropa', cliente_proveedor: 'Shein', descripcion: 'Shein', metodo_pago: 'Tarjeta', monto: 8420, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g13', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Carro', cliente_proveedor: 'Carro Mazda', descripcion: 'Gastos carro Mazda', metodo_pago: 'Transferencia', monto: 208000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g14', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Restaurante', descripcion: 'Restaurante', metodo_pago: 'Tarjeta', monto: 146300, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g15', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Delivery', cliente_proveedor: 'Rappi', descripcion: 'Rappi', metodo_pago: 'Tarjeta', monto: 48000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g16', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Fraude/Disputa', subcategoria: 'No reconocido', cliente_proveedor: 'Apple.com', descripcion: 'Apple.com (no reconocido)', metodo_pago: 'Tarjeta', monto: 120000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g17', fecha: '2026-02-02', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Servicios', subcategoria: 'Celular', cliente_proveedor: 'Celular', descripcion: 'Plan de celular', metodo_pago: 'Transferencia', monto: 100000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-02T00:00:00Z' },
  { id: 'feb-g18', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Tacos House', descripcion: 'Tacos House', metodo_pago: 'Transferencia', monto: 43000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g19', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Suplementos', cliente_proveedor: 'Suplementos', descripcion: 'Pre-entreno', metodo_pago: 'Transferencia', monto: 15000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g20', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Corto plazo', cliente_proveedor: 'Daniel', descripcion: 'Deuda Daniel', metodo_pago: 'Transferencia', monto: 25000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g21', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Mercado/Hogar', subcategoria: 'Supermercado', cliente_proveedor: 'PriceSmart', descripcion: 'PriceSmart', metodo_pago: 'Transferencia', monto: 52000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g22', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Mercado/Hogar', subcategoria: 'Supermercado', cliente_proveedor: 'PriceSmart', descripcion: 'Comida PriceSmart', metodo_pago: 'Transferencia', monto: 31000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g23', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Comida', cliente_proveedor: 'Ángela', descripcion: 'Comida Ángela', metodo_pago: 'Transferencia', monto: 28000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g24', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Regalo', cliente_proveedor: 'Ana María', descripcion: 'Regalo Ana María', metodo_pago: 'Transferencia', monto: 25000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g25', fecha: '2026-02-15', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Salud/Cuidado', subcategoria: 'Medicamentos', cliente_proveedor: 'Farmacia', descripcion: 'Minoxidil', metodo_pago: 'Transferencia', monto: 34000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-15T00:00:00Z' },
  { id: 'feb-g26', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Peaje', cliente_proveedor: 'Peaje', descripcion: 'Peaje', metodo_pago: 'Transferencia', monto: 20000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g27', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Café', cliente_proveedor: 'Café', descripcion: 'Café', metodo_pago: 'Transferencia', monto: 6000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g28', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Restaurante', descripcion: 'Hamburguesa', metodo_pago: 'Transferencia', monto: 60000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g29', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Taxi/Uber', cliente_proveedor: 'Uber', descripcion: 'Uber', metodo_pago: 'Transferencia', monto: 15000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g30', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Helado', cliente_proveedor: 'Heladería', descripcion: 'Helado', metodo_pago: 'Transferencia', monto: 18000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g31', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Sushi Cai Cai', descripcion: 'Sushi Cai Cai', metodo_pago: 'Transferencia', monto: 72500, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g32', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Parqueadero', cliente_proveedor: 'Aeropuerto', descripcion: 'Parqueadero aeropuerto', metodo_pago: 'Transferencia', monto: 7000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g33', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Corto plazo', cliente_proveedor: 'Wilson', descripcion: 'Pago deuda Wilson', metodo_pago: 'Transferencia', monto: 91000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g34', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Gasolinera', descripcion: 'Gasolina', metodo_pago: 'Transferencia', monto: 50000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g35', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Suplementos', cliente_proveedor: 'Suplementos', descripcion: 'Betalanina', metodo_pago: 'Transferencia', monto: 15000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g36', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Antojo', cliente_proveedor: 'Granizados', descripcion: 'Granizados', metodo_pago: 'Transferencia', monto: 18000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g37', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Comida Zamu', descripcion: 'Comida Zamu', metodo_pago: 'Transferencia', monto: 45000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g38', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Antojo', cliente_proveedor: 'Granizados', descripcion: 'Granizado 1', metodo_pago: 'Transferencia', monto: 25000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g39', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Antojo', cliente_proveedor: 'Granizados', descripcion: 'Granizado 2', metodo_pago: 'Transferencia', monto: 25000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g40', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Tierra Querida', descripcion: 'Tierra Querida', metodo_pago: 'Transferencia', monto: 36000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g41', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Gasolinera', descripcion: 'Gasolina', metodo_pago: 'Transferencia', monto: 30000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },
  { id: 'feb-g42', fecha: '2026-02-18', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Ocio/Deporte', subcategoria: 'Deporte', cliente_proveedor: 'Fútbol', descripcion: 'Torneo fútbol', metodo_pago: 'Transferencia', monto: 40000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-18T00:00:00Z' },

  // Ingreso proyecto febrero
  { id: 'feb-p1', fecha: '2026-02-27', periodo: '2026-02', año: 2026, mes: 2, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Proyecto', subcategoria: 'IA', cliente_proveedor: 'JUAN DAVID RAMIREZ', descripcion: 'BOT TAOWOK (Abono)', metodo_pago: 'Transferencia', monto: 250000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-02-27T00:00:00Z', proyecto_id: 'p4' },

  // Ingresos variables adicionales febrero
  { id: 'feb-v1', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Ingreso variable', subcategoria: 'Servicio', cliente_proveedor: 'Masivos B', descripcion: 'Masivo B', metodo_pago: 'Transferencia', monto: 480000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-v2', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'Proyecto', subcategoria: 'Retainer', cliente_proveedor: 'Juan Diego Cluenza', descripcion: 'Segunda cuota Cluenza', metodo_pago: 'Transferencia', monto: 914000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z', proyecto_id: 'p2' },

  // Gastos variables adicionales febrero
  { id: 'feb-g43', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Hogar', subcategoria: 'Pago hogar', cliente_proveedor: 'Hogar', descripcion: 'Pago hogar', metodo_pago: 'Transferencia', monto: 320000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g44', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Bebidas', cliente_proveedor: 'Bar', descripcion: 'Cervezas', metodo_pago: 'Transferencia', monto: 25000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g45', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Barbería', cliente_proveedor: 'Barbería', descripcion: 'Barbería', metodo_pago: 'Transferencia', monto: 25000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g46', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Peaje', cliente_proveedor: 'Peaje', descripcion: 'Peaje', metodo_pago: 'Transferencia', monto: 50000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g47', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Gasolinera', descripcion: 'Gasolina', metodo_pago: 'Transferencia', monto: 40000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g48', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Perros Calientes', descripcion: 'Perros calientes', metodo_pago: 'Transferencia', monto: 30000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g49', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Hotel/Restaurante', cliente_proveedor: 'Hotel', descripcion: 'Hotel 2 (salida)', metodo_pago: 'Transferencia', monto: 243000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g50', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Familia/Regalos', subcategoria: 'Gastos', cliente_proveedor: 'Familia', descripcion: 'Gastos familia', metodo_pago: 'Transferencia', monto: 110000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g51', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Gasolinera', descripcion: 'Gasolina', metodo_pago: 'Transferencia', monto: 79000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  // feb-g52 (eliminado por duplicidad — ya está detallado en los consumos individuales)
  { id: 'feb-g53', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Gym', cliente_proveedor: 'Gym Animal', descripcion: 'Gym Animal Health', metodo_pago: 'Transferencia', monto: 160000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g54', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Taxi/Uber', cliente_proveedor: 'Uber', descripcion: 'Uber', metodo_pago: 'Efectivo', monto: 34000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-02-28T00:00:00Z' },
  { id: 'feb-g55', fecha: '2026-02-28', periodo: '2026-02', año: 2026, mes: 2, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Pasaje', cliente_proveedor: 'Transporte', descripcion: 'Pago pasaje', metodo_pago: 'Efectivo', monto: 5000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-02-28T00:00:00Z' },

  // ─────────────── MARZO 2026 ─────────────── (manual — valores reales corregidos)
  // Gastos fijos operativos marzo
  { id: 'mar-ofi', fecha: '2026-03-01', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Oficina', cliente_proveedor: 'Arrendador', descripcion: 'Alquiler oficina', metodo_pago: 'Transferencia', monto: 750000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-01T08:00:00Z' },
  { id: 'mar-int', fecha: '2026-03-01', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Internet/Celular', cliente_proveedor: 'Movistar', descripcion: 'Internet y celular', metodo_pago: 'Transferencia', monto: 75000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-01T08:00:00Z' },
  { id: 'mar-ser', fecha: '2026-03-01', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Operativos', subcategoria: 'Servicios', cliente_proveedor: 'EPM', descripcion: 'Servicios públicos', metodo_pago: 'Transferencia', monto: 150000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-01T08:00:00Z' },
  { id: 'mar-gas', fecha: '2026-03-05', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Gasolina', cliente_proveedor: 'Primax', descripcion: 'Gasolina carro', metodo_pago: 'Efectivo', monto: 300000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-03-05T08:00:00Z' },
  { id: 'mar-n8n', fecha: '2026-03-10', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Herramientas', subcategoria: 'Suscripción', cliente_proveedor: 'n8n', descripcion: 'Suscripción n8n', metodo_pago: 'Tarjeta', monto: 80000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: '2026-03-10T08:00:00Z' },
  { id: 'mar-anti', fecha: '2026-03-10', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Gasto', categoria: 'Herramientas', subcategoria: 'Suscripción', cliente_proveedor: 'Antigravity', descripcion: 'Suscripción Antigravity', metodo_pago: 'Tarjeta', monto: 80000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'TC Visa', created_at: '2026-03-10T08:00:00Z' },
  { id: 'mar-gym', fecha: '2026-03-02', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Gym', cliente_proveedor: 'SmartFit', descripcion: 'Mensualidad Gym', metodo_pago: 'Tarjeta', monto: 160000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'TC Visa', created_at: '2026-03-02T08:00:00Z' },
  { id: 'mar-barb', fecha: '2026-03-20', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Bienestar', subcategoria: 'Barbería', cliente_proveedor: 'Barber Shop', descripcion: 'Corte de cabello', metodo_pago: 'Efectivo', monto: 100000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Billetera', created_at: '2026-03-20T08:00:00Z' },
  { id: 'mar-dvictor', fecha: '2026-03-15', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Víctor', cliente_proveedor: 'Víctor', descripcion: 'Pago deuda Víctor', metodo_pago: 'Transferencia', monto: 500000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-15T08:00:00Z' },
  { id: 'mar-dbanco', fecha: '2026-03-30', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Banco Nacional', cliente_proveedor: 'Banco Nacional', descripcion: 'Cuota crédito bancario', metodo_pago: 'Transferencia', monto: 900000, recurrente: true, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-30T08:00:00Z' },

  // MRR Marzo — valores REALES corregidos
  { id: 'mar-mrr1', fecha: '2026-03-20', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare Soporte', cliente_proveedor: 'KP Skincare Soporte', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 745000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-20T08:00:00Z' },
  { id: 'mar-mrr2', fecha: '2026-03-20', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare IA', cliente_proveedor: 'KP Skincare IA', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 560000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-20T08:00:00Z' },
  { id: 'mar-mrr3', fecha: '2026-03-15', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini WhatsApp', cliente_proveedor: 'Motel Santorini WhatsApp', descripcion: 'Cobro Mensual', metodo_pago: 'Efectivo', monto: 516000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-15T08:00:00Z' },
  { id: 'mar-mrr4', fecha: '2026-03-01', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini 1', cliente_proveedor: 'Motel Santorini 1', descripcion: 'Cobro Mensual', metodo_pago: 'Efectivo', monto: 400000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-01T08:00:00Z' },
  { id: 'mar-mrr5', fecha: '2026-03-05', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'La Vera Massa', cliente_proveedor: 'La Vera Massa', descripcion: 'Cobro Mensual', metodo_pago: 'Transferencia', monto: 350000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-05T08:00:00Z' },
  { id: 'mar-mrr7', fecha: '2026-03-25', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Taowok', cliente_proveedor: 'Taowok', descripcion: 'Cobro Mensual (pausa — cobro parcial)', metodo_pago: 'Transferencia', monto: 120000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-25T08:00:00Z' },
  { id: 'mar-mrr8', fecha: '2026-03-20', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'SM DIGITALS', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare Automatización', cliente_proveedor: 'KP Skincare', descripcion: 'MRR Automatización (nuevo)', metodo_pago: 'Transferencia', monto: 265000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-03-20T08:00:00Z' },

  // Gastos marzo adicionales
  { id: 'mar-g10', fecha: '2026-03-20', periodo: '2026-03', año: 2026, mes: 3, space_id: 'business', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Tarjeta', cliente_proveedor: 'Tarjeta crédito', descripcion: 'Pago tarjeta crédito', metodo_pago: 'Transferencia', monto: 1200000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-20T00:00:00Z' },
  { id: 'mar-g11', fecha: '2026-03-25', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Corto plazo', cliente_proveedor: 'Wilson', descripcion: 'Pago deuda Wilson', metodo_pago: 'Transferencia', monto: 120000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-25T00:00:00Z' },
  { id: 'mar-g12', fecha: '2026-03-25', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Corto plazo', cliente_proveedor: 'José Candela', descripcion: 'Pago deuda José Candela', metodo_pago: 'Transferencia', monto: 125000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-25T00:00:00Z' },
  { id: 'mar-g13', fecha: '2026-03-28', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Ocio', subcategoria: 'Discoteca', cliente_proveedor: 'Discoteca', descripcion: 'Salida discoteca', metodo_pago: 'Transferencia', monto: 300000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-28T00:00:00Z' },
  { id: 'mar-g14', fecha: '2026-03-28', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Comida/Ocio', subcategoria: 'Restaurante', cliente_proveedor: 'Restaurante', descripcion: 'Comida', metodo_pago: 'Transferencia', monto: 100000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-28T00:00:00Z' },
  { id: 'mar-g15', fecha: '2026-03-29', periodo: '2026-03', año: 2026, mes: 3, space_id: 'personal', unidad: 'Personal', tipo_movimiento: 'Gasto', categoria: 'Ocio/Deporte', subcategoria: 'Fútbol', cliente_proveedor: 'Fútbol', descripcion: 'Salida fútbol sábado', metodo_pago: 'Transferencia', monto: 20000, recurrente: false, estado: 'Pagado', impacto: 'Privado', cuenta: 'Bancolombia', created_at: '2026-03-29T00:00:00Z' },
  // Ingresos Abril 2026
  { id: 'm_apr_i1', fecha: '2026-04-05', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'Proyecto', subcategoria: 'Upgoing', cliente_proveedor: 'Upgoing', descripcion: 'Upgoing (10%)', metodo_pago: 'Transferencia', monto: 272000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i2', fecha: '2026-04-09', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare', cliente_proveedor: 'KP Skincare', descripcion: 'Mensualidad KP', metodo_pago: 'Transferencia', monto: 727000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i3', fecha: '2026-04-15', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'Ingreso variable', subcategoria: 'Servicio', cliente_proveedor: 'Impulsy', descripcion: 'Impulsy Tasks', metodo_pago: 'Transferencia', monto: 92000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i4', fecha: '2026-04-15', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini 1', cliente_proveedor: 'Santorini', descripcion: 'Pago Santorini', metodo_pago: 'Transferencia', monto: 400000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i5', fecha: '2026-04-15', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'Motel Santorini WhatsApp', cliente_proveedor: 'Santorini', descripcion: 'Pago Santorini WhatsApp', metodo_pago: 'Transferencia', monto: 685000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i6', fecha: '2026-04-15', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'MRR', subcategoria: 'KP Skincare', cliente_proveedor: 'KP Skincare', descripcion: 'Pago KP Extra', metodo_pago: 'Transferencia', monto: 852000, recurrente: true, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i7', fecha: '2026-04-15', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Ingreso', categoria: 'Proyecto', subcategoria: 'Velik', cliente_proveedor: 'Velik Beauty House', descripcion: 'Proyecto Velik', metodo_pago: 'Transferencia', monto: 1080000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_i8', fecha: '2026-04-07', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Ingreso', categoria: 'Préstamo', subcategoria: 'Ingreso', cliente_proveedor: 'Tercero', descripcion: 'Préstamo recibido', metodo_pago: 'Transferencia', monto: 4000000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  // Gastos Abril 2026
  { id: 'm_apr_f0', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Préstamo', cliente_proveedor: 'Crédito', descripcion: 'Crédito', metodo_pago: 'Transferencia', monto: 742000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f1', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Préstamo', cliente_proveedor: 'Crédito', descripcion: 'Crédito', metodo_pago: 'Transferencia', monto: 785000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f2', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Préstamo', cliente_proveedor: 'Crédito', descripcion: 'Crédito', metodo_pago: 'Transferencia', monto: 33000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f3', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Préstamo', cliente_proveedor: 'Crédito', descripcion: 'Crédito', metodo_pago: 'Transferencia', monto: 28000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f4', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Préstamo', cliente_proveedor: 'Crédito', descripcion: 'Crédito', metodo_pago: 'Transferencia', monto: 45000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f5', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Mercado/Hogar', subcategoria: 'Vivienda', cliente_proveedor: 'Apartamento Santa Marta', descripcion: 'Apartamento Santa Marta', metodo_pago: 'Transferencia', monto: 766000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f6', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Amortización', cliente_proveedor: 'Deuda Víctor', descripcion: 'Deuda Víctor', metodo_pago: 'Transferencia', monto: 500000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f7', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Amortización', cliente_proveedor: 'Abono Wilson', descripcion: 'Abono Wilson', metodo_pago: 'Transferencia', monto: 100000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_f8', fecha: '2026-04-01', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Deuda', subcategoria: 'Amortización', cliente_proveedor: 'Abono Wilson', descripcion: 'Abono Wilson', metodo_pago: 'Transferencia', monto: 14500, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_inv1', fecha: '2026-04-30', periodo: '2026-04', año: 2026, mes: 4, unidad: 'SM DIGITALS', space_id: 'business', tipo_movimiento: 'Gasto', categoria: 'Inversión', subcategoria: 'Evento', cliente_proveedor: 'Evento', descripcion: 'Evento 30 abril', metodo_pago: 'Transferencia', monto: 500000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_trip1', fecha: '2026-04-11', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Viaje', subcategoria: 'Santa Marta', cliente_proveedor: 'Viaje', descripcion: 'Viaje Santa Marta', metodo_pago: 'Transferencia', monto: 2425000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_o1', fecha: '2026-04-15', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Otros', subcategoria: 'Préstamo', cliente_proveedor: 'Tercero', descripcion: 'Dinero prestado a tercero', metodo_pago: 'Transferencia', monto: 400000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Bancolombia', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_c1', fecha: '2026-04-10', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Ocio', subcategoria: 'Comida', cliente_proveedor: 'Varios', descripcion: 'Gastos Comida (Torta, Mercado, Perros, etc)', metodo_pago: 'Efectivo', monto: 1194500, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Efectivo', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_t1', fecha: '2026-04-12', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Transporte', subcategoria: 'Movilidad', cliente_proveedor: 'Uber/Gasolina', descripcion: 'Uber y Gasolina', metodo_pago: 'Efectivo', monto: 122000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Efectivo', created_at: '2026-04-27T10:44:00Z' },
  { id: 'm_apr_v1', fecha: '2026-04-08', periodo: '2026-04', año: 2026, mes: 4, unidad: 'Personal', space_id: 'personal', tipo_movimiento: 'Gasto', categoria: 'Compras', subcategoria: 'Varios', cliente_proveedor: 'Varios', descripcion: 'Compras varias (Gafas, Camiseta, Barbería, etc)', metodo_pago: 'Efectivo', monto: 967000, recurrente: false, estado: 'Pagado', impacto: 'Core', cuenta: 'Efectivo', created_at: '2026-04-27T10:44:00Z' }
];

export const mockClientesMRR: ClienteMRR[] = [
  { id: 'm1', cliente: 'KP Skincare Soporte', servicio: 'Soporte mensual', valor_mensual: 745000, dia_cobro: 1, estado: 'Activo', fecha_inicio: '2025-09-01', metodo_pago: 'Transferencia' },
  { id: 'm2', cliente: 'KP Skincare IA', servicio: 'IA mensual', valor_mensual: 580000, dia_cobro: 1, estado: 'Activo', fecha_inicio: '2025-06-01', metodo_pago: 'Transferencia' },
  { id: 'm8', cliente: 'KP Skincare Automatización', servicio: 'Automatización mensual', valor_mensual: 265000, dia_cobro: 1, estado: 'Activo', fecha_inicio: '2026-03-01', metodo_pago: 'Transferencia' },
  { id: 'm3', cliente: 'Motel Santorini WhatsApp', servicio: 'Bot WhatsApp', valor_mensual: 516000, dia_cobro: 16, estado: 'Activo', fecha_inicio: '2025-04-01', metodo_pago: 'Efectivo' },
  { id: 'm4', cliente: 'Motel Santorini 1', servicio: 'Soporte web', valor_mensual: 400000, dia_cobro: 10, estado: 'Activo', fecha_inicio: '2025-01-01', metodo_pago: 'Efectivo' },
  { id: 'm5', cliente: 'La Vera Massa', servicio: 'Marketing digital', valor_mensual: 350000, dia_cobro: 1, estado: 'Activo', fecha_inicio: '2025-01-01', metodo_pago: 'Transferencia' },
  { id: 'm6', cliente: 'S.O.S Tenis', servicio: 'Soporte mensual', valor_mensual: 250000, dia_cobro: 10, estado: 'Pausado', fecha_inicio: '2025-03-01', metodo_pago: 'Transferencia' },
  { id: 'm7', cliente: 'Taowok', servicio: 'Bot IA', valor_mensual: 250000, dia_cobro: 25, estado: 'Pausado', fecha_inicio: '2025-07-01', metodo_pago: 'Transferencia' },
];

export const mockProyectos: Proyecto[] = [
  { id: 'p1', cliente: 'Proyecto F', nombre_proyecto: 'Proyecto Frei', tipo: 'Consultoría', valor_total: 1000000, anticipo: 1000000, cobrado: 1000000, pendiente: 0, fecha_inicio: '2026-01-10', estado: 'Completado', rentabilidad_estimada: 70, fase: 'Finalizado' },
  { id: 'p2', cliente: 'JUAN DIEGO CLUENZA', nombre_proyecto: 'PAGO SEGUNDA CUOTA CLUENZA', tipo: 'Retainer', valor_total: 914000, anticipo: 0, cobrado: 914000, pendiente: 0, fecha_inicio: '2026-01-22', estado: 'Completado', rentabilidad_estimada: 65, fase: 'Finalizado' },
  { id: 'p3', cliente: 'FELIPE HERNANDE', nombre_proyecto: 'UP GOING GROUP', tipo: 'Desarrollo', valor_total: 1303750, anticipo: 0, cobrado: 1303750, pendiente: 0, fecha_inicio: '2026-02-28', estado: 'Completado', rentabilidad_estimada: 80, fase: 'Finalizado' },
  { id: 'p4', cliente: 'JUAN DAVID RAMIREZ', nombre_proyecto: 'BOT TAOWOK', tipo: 'One-off', valor_total: 500000, anticipo: 0, cobrado: 250000, pendiente: 250000, fecha_inicio: '2026-02-27', estado: 'En Proceso', rentabilidad_estimada: 75, fase: 'Desarrollo' },
  { id: 'p5', cliente: 'JUAN DIEGO', nombre_proyecto: 'KOMMO DIGITAL', tipo: 'One-off', valor_total: 500000, anticipo: 0, cobrado: 0, pendiente: 500000, fecha_inicio: '2026-02-27', estado: 'En Proceso', rentabilidad_estimada: 80, fase: 'Desarrollo' },
  { id: 'p6', cliente: 'KARINA PLASENCIA', nombre_proyecto: 'SEMESTRE KP SKINCARE', tipo: 'Retainer', valor_total: 3371625, anticipo: 0, cobrado: 1110000, pendiente: 2261625, fecha_inicio: '2026-03-05', estado: 'En Proceso', rentabilidad_estimada: 60, fase: 'Desarrollo' }
];

export const mockDeudas: Deuda[] = [
  { id: 'd1', acreedor: 'Víctor', tipo: 'Préstamo', saldo_inicial: 15000000, cuota_mensual: 500000, pagado: 1000000, saldo_restante: 14000000, fecha_pago: '2026-03-15', estado: 'Al día' },
  { id: 'd2', acreedor: 'Banco Nacional', tipo: 'Crédito Bancario', saldo_inicial: 30000000, cuota_mensual: 900000, pagado: 2000000, saldo_restante: 28000000, fecha_pago: '2026-03-30', estado: 'Al día' },
  { id: 'd3', acreedor: 'Wilson', tipo: 'Préstamo personal', saldo_inicial: 272000, cuota_mensual: 0, pagado: 120000, saldo_restante: 152000, fecha_pago: '2026-03-25', estado: 'Al día' },
  { id: 'd4', acreedor: 'José Candela', tipo: 'Préstamo personal', saldo_inicial: 400000, cuota_mensual: 0, pagado: 125000, saldo_restante: 275000, fecha_pago: '2026-03-25', estado: 'Al día' },
];

export const mockPresupuestos: Presupuesto[] = [
  { id: 'b0', periodo: '2026-04', unidad: 'SM DIGITALS', categoria: 'Operativos', presupuesto: 5000000, real: 4108000, diferencia: 892000 },
  { id: 'b1', periodo: '2026-03', unidad: 'SM DIGITALS', categoria: 'Operativos', presupuesto: 2000000, real: 1435000, diferencia: 565000 },
  { id: 'b2', periodo: '2026-02', unidad: 'SM DIGITALS', categoria: 'Operativos', presupuesto: 2000000, real: 1435000, diferencia: 565000 },
  { id: 'b3', periodo: '2026-01', unidad: 'SM DIGITALS', categoria: 'Operativos', presupuesto: 2000000, real: 1435000, diferencia: 565000 }
];
